baseURL = "https://swapnilbawane.github.io/"
title = "Swapnil Bawane"
theme = "PaperMod"
languageCode = "en-us"
[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  [params.author]
    name = "Swapnil Bawane"
